name: company_project

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_bloc: ^4.0.0
  equatable: ^1.0.1
  http: ^0.12.0+3
  shared_preferences: ^0.5.6
  cached_network_image: ^2.0.0
  json_annotation: ^3.0.1
  image_picker: ^0.6.2+3
  liquid_progress_indicator: ^0.3.2
  pull_to_refresh: ^1.5.7
  heatmap_calendar: ^1.2.5
  test: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  json_serializable: ^3.2.5


flutter:
  assets:
    - images/
  uses-material-design: true
